# Generated by Django 5.0.3 on 2024-04-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='support',
            field=models.CharField(default='آنلاین', max_length=255),
        ),
    ]
