# Generated by Django 5.0.3 on 2024-04-03 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_details_progress_teacher_title_alter_details_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
