# Generated by Django 5.0.3 on 2024-04-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_details_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='requirement',
            field=models.CharField(default='بدون پیشنیاز', max_length=255),
        ),
    ]
